export const COFFEE_DATA = [
  {
    id: 1,
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    image: '../../src/assets/coffee/expresso.png',
    tag: ['tradicional'],
    price: 9.9,
  },
  {
    id: 2,
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    image: '../../src/assets/coffee/americano.png',
    tag: ['tradicional'],
    price: 9.9,
  },
  {
    id: 3,
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    image: '../../src/assets/coffee/expresso-cremoso.png',
    tag: ['tradicional'],
    price: 9.9,
  },
  {
    id: 4,
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    image: '../../src/assets/coffee/cafe-gelado.png',
    tag: ['tradicional', 'gelado'],
    price: 9.9,
  },
  {
    id: 5,
    name: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    image: '../../src/assets/coffee/cafe-com-leite.png',
    tag: ['tradicional', 'com leite'],
    price: 9.9,
  },
  {
    id: 6,
    name: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    image: '../../src/assets/coffee/latte.png',
    tag: ['tradicional', 'com leite'],
    price: 9.9,
  },
  {
    id: 7,
    name: 'Cappuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    image: '../../src/assets/coffee/capuccino.png',
    tag: ['tradicional', 'com leite'],
    price: 9.9,
  },
  {
    id: 8,
    name: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    image: '../../src/assets/coffee/macchiato.png',
    tag: ['tradicional', 'com leite'],
    price: 9.9,
  },
  {
    id: 9,
    name: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    image: '../../src/assets/coffee/mochaccino.png',
    tag: ['tradicional', 'com leite'],
    price: 9.9,
  },
  {
    id: 10,
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    image: '../../src/assets/coffee/chocolate-quente.png',
    tag: ['tradicional', 'com leite'],
    price: 9.9,
  },
  {
    id: 11,
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    image: '../../src/assets/coffee/cubano.png',
    tag: ['tradicional', 'gelado', 'alcoólico'],
    price: 9.9,
  },
  {
    id: 12,
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    image: '../../src/assets/coffee/havaiano.png',
    tag: ['especial'],
    price: 9.9,
  },
  {
    id: 13,
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    image: '../../src/assets/coffee/arabe.png',
    tag: ['especial'],
    price: 9.9,
  },
  {
    id: 14,
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    image: '../../src/assets/coffee/irlandes.png',
    tag: ['especial', 'alcoólico'],
    price: 9.9,
  },
]
